id: IBE446333
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-06T15:32:44+00:00'
last_modified: '2022-06-07T13:54:12.360106+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21807
  title: གསུང་འབུམ། མཁྱེན་བརྩེའི་དབང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A4D4:
      image_group_id: I0506
      title: ''
      total_pages: 498
      order: 1
      base_file: A4D4.txt
    A665:
      image_group_id: I0507
      title: ''
      total_pages: 492
      order: 2
      base_file: A665.txt
    '3548':
      image_group_id: I0508
      title: ''
      total_pages: 738
      order: 3
      base_file: 3548.txt
    '5974':
      image_group_id: I0509
      title: ''
      total_pages: 716
      order: 4
      base_file: 5974.txt
    070B:
      image_group_id: I0510
      title: ''
      total_pages: 614
      order: 5
      base_file: 070B.txt
    B643:
      image_group_id: I0511
      title: ''
      total_pages: 528
      order: 6
      base_file: B643.txt
    602A:
      image_group_id: I0512
      title: ''
      total_pages: 550
      order: 7
      base_file: 602A.txt
    05F2:
      image_group_id: I0513
      title: ''
      total_pages: 528
      order: 8
      base_file: 05F2.txt
    434D:
      image_group_id: I0514
      title: ''
      total_pages: 464
      order: 9
      base_file: 434D.txt
    B9BB:
      image_group_id: I0515
      title: ''
      total_pages: 546
      order: 10
      base_file: B9BB.txt
    6E7D:
      image_group_id: I0516
      title: ''
      total_pages: 542
      order: 11
      base_file: 6E7D.txt
    AB55:
      image_group_id: I0517
      title: ''
      total_pages: 544
      order: 12
      base_file: AB55.txt
    '4523':
      image_group_id: I0518
      title: ''
      total_pages: 600
      order: 13
      base_file: 4523.txt
    61A7:
      image_group_id: I0519
      title: ''
      total_pages: 614
      order: 14
      base_file: 61A7.txt
    2AED:
      image_group_id: I0520
      title: ''
      total_pages: 578
      order: 15
      base_file: 2AED.txt
    4BC4:
      image_group_id: I0521
      title: ''
      total_pages: 576
      order: 16
      base_file: 4BC4.txt
    06EB:
      image_group_id: I0522
      title: ''
      total_pages: 538
      order: 17
      base_file: 06EB.txt
    954A:
      image_group_id: I0523
      title: ''
      total_pages: 524
      order: 18
      base_file: 954A.txt
    '1015':
      image_group_id: I0524
      title: ''
      total_pages: 536
      order: 19
      base_file: 1015.txt
    86FB:
      image_group_id: I0525
      title: ''
      total_pages: 556
      order: 20
      base_file: 86FB.txt
    A5CC:
      image_group_id: I0526
      title: ''
      total_pages: 564
      order: 21
      base_file: A5CC.txt
    DFED:
      image_group_id: I0527
      title: ''
      total_pages: 624
      order: 22
      base_file: DFED.txt
    5F91:
      image_group_id: I0528
      title: ''
      total_pages: 466
      order: 23
      base_file: 5F91.txt
    33C0:
      image_group_id: I0529
      title: ''
      total_pages: 396
      order: 24
      base_file: 33C0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
