id: IBE446333
legacy_id: P000821
ocr_import_info:
  bdrc_scan_id: W21807
  source: bdrc
  ocr_info:
    timestamp: '2021-04-06T15:30:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T14:25:24.433872+00:00'
last_modified: 2022-09-01 22:32:10.378977
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W21807
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW21807
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མཁྱེན་བརྩེའི་དབང་པོ།
  author: མཁྱེན་བརྩེའི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.7355583756020084
  ocr_word_median_confidence_index: 0.8
quality: null
bases:
  I0527:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0527
      total_pages: 624
      volume_number: 22
      volume_pages_bdrc_intro: 2
    order: 22
    base_file: I0527.txt
    statistics:
      ocr_word_median_confidence_index: 0.79
      ocr_word_mean_confidence_index: 0.728570180527591
    legacy_id: v022
  I0519:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0519
      total_pages: 614
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I0519.txt
    statistics:
      ocr_word_median_confidence_index: 0.78
      ocr_word_mean_confidence_index: 0.7104379153804249
    legacy_id: v014
  I0525:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0525
      total_pages: 556
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I0525.txt
    statistics:
      ocr_word_median_confidence_index: 0.77
      ocr_word_mean_confidence_index: 0.7079832037228381
    legacy_id: v020
  I0516:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0516
      total_pages: 542
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I0516.txt
    statistics:
      ocr_word_median_confidence_index: 0.86
      ocr_word_mean_confidence_index: 0.782270454235329
    legacy_id: v011
  I0518:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0518
      total_pages: 600
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I0518.txt
    statistics:
      ocr_word_median_confidence_index: 0.84
      ocr_word_mean_confidence_index: 0.7599726427262236
    legacy_id: v013
  I0524:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0524
      total_pages: 536
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I0524.txt
    statistics:
      ocr_word_median_confidence_index: 0.81
      ocr_word_mean_confidence_index: 0.7512949680466574
    legacy_id: v019
  I0521:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0521
      total_pages: 576
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I0521.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6955091372045337
    legacy_id: v016
  I0522:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0522
      total_pages: 538
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I0522.txt
    statistics:
      ocr_word_median_confidence_index: 0.68
      ocr_word_mean_confidence_index: 0.6429634024814198
    legacy_id: v017
  I0506:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0506
      total_pages: 498
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0506.txt
    statistics:
      ocr_word_median_confidence_index: 0.85
      ocr_word_mean_confidence_index: 0.7745482803969235
    legacy_id: v001
  I0528:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0528
      total_pages: 466
      volume_number: 23
      volume_pages_bdrc_intro: 2
    order: 23
    base_file: I0528.txt
    statistics:
      ocr_word_median_confidence_index: 0.76
      ocr_word_mean_confidence_index: 0.7019198650034996
    legacy_id: v023
  I0529:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0529
      total_pages: 396
      volume_number: 24
      volume_pages_bdrc_intro: 2
    order: 24
    base_file: I0529.txt
    statistics:
      ocr_word_median_confidence_index: 0.83
      ocr_word_mean_confidence_index: 0.7504566581944307
    legacy_id: v024
  I0513:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0513
      total_pages: 528
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I0513.txt
    statistics:
      ocr_word_median_confidence_index: 0.78
      ocr_word_mean_confidence_index: 0.7135601957699095
    legacy_id: v008
  I0526:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0526
      total_pages: 564
      volume_number: 21
      volume_pages_bdrc_intro: 2
    order: 21
    base_file: I0526.txt
    statistics:
      ocr_word_median_confidence_index: 0.8
      ocr_word_mean_confidence_index: 0.727937839284349
    legacy_id: v021
  I0523:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0523
      total_pages: 524
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I0523.txt
    statistics:
      ocr_word_median_confidence_index: 0.79
      ocr_word_mean_confidence_index: 0.7313552391865268
    legacy_id: v018
  I0507:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0507
      total_pages: 492
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0507.txt
    statistics:
      ocr_word_median_confidence_index: 0.87
      ocr_word_mean_confidence_index: 0.7952016642192854
    legacy_id: v002
  I0509:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0509
      total_pages: 716
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I0509.txt
    statistics:
      ocr_word_median_confidence_index: 0.82
      ocr_word_mean_confidence_index: 0.7532053523280138
    legacy_id: v004
  I0515:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0515
      total_pages: 546
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I0515.txt
    statistics:
      ocr_word_median_confidence_index: 0.78
      ocr_word_mean_confidence_index: 0.722791920824076
    legacy_id: v010
  I0514:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0514
      total_pages: 464
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I0514.txt
    statistics:
      ocr_word_median_confidence_index: 0.87
      ocr_word_mean_confidence_index: 0.791581344337869
    legacy_id: v009
  I0511:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0511
      total_pages: 528
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I0511.txt
    statistics:
      ocr_word_median_confidence_index: 0.8
      ocr_word_mean_confidence_index: 0.7294704090325003
    legacy_id: v006
  I0508:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0508
      total_pages: 738
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I0508.txt
    statistics:
      ocr_word_median_confidence_index: 0.84
      ocr_word_mean_confidence_index: 0.7724401809123579
    legacy_id: v003
  I0512:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0512
      total_pages: 550
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I0512.txt
    statistics:
      ocr_word_median_confidence_index: 0.81
      ocr_word_mean_confidence_index: 0.7482725441212024
    legacy_id: v007
  I0517:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0517
      total_pages: 544
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I0517.txt
    statistics:
      ocr_word_median_confidence_index: 0.78
      ocr_word_mean_confidence_index: 0.7183609638230753
    legacy_id: v012
  I0520:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0520
      total_pages: 578
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I0520.txt
    statistics:
      ocr_word_median_confidence_index: 0.8
      ocr_word_mean_confidence_index: 0.7304470501149715
    legacy_id: v015
  I0510:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0510
      total_pages: 614
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I0510.txt
    statistics:
      ocr_word_median_confidence_index: 0.77
      ocr_word_mean_confidence_index: 0.7111374839561748
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
